/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.oldschool.user.registration.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the USMember service. Represents a row in the &quot;US_USMember&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.oldschool.user.registration.model.impl.USMemberModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.oldschool.user.registration.model.impl.USMemberImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a u s member model instance should use the {@link USMember} interface instead.
 * </p>
 *
 * @author Sr. Eladio
 * @see USMember
 * @see com.oldschool.user.registration.model.impl.USMemberImpl
 * @see com.oldschool.user.registration.model.impl.USMemberModelImpl
 * @generated
 */
public interface USMemberModel extends BaseModel<USMember> {
	/**
	 * Gets the primary key of this u s member.
	 *
	 * @return the primary key of this u s member
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this u s member
	 *
	 * @param pk the primary key of this u s member
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the member id of this u s member.
	 *
	 * @return the member id of this u s member
	 */
	public long getMemberId();

	/**
	 * Sets the member id of this u s member.
	 *
	 * @param memberId the member id of this u s member
	 */
	public void setMemberId(long memberId);

	/**
	 * Gets the member first name of this u s member.
	 *
	 * @return the member first name of this u s member
	 */
	@AutoEscape
	public String getMemberFirstName();

	/**
	 * Sets the member first name of this u s member.
	 *
	 * @param memberFirstName the member first name of this u s member
	 */
	public void setMemberFirstName(String memberFirstName);

	/**
	 * Gets the member last name of this u s member.
	 *
	 * @return the member last name of this u s member
	 */
	@AutoEscape
	public String getMemberLastName();

	/**
	 * Sets the member last name of this u s member.
	 *
	 * @param memberLastName the member last name of this u s member
	 */
	public void setMemberLastName(String memberLastName);

	/**
	 * Gets the member phone number of this u s member.
	 *
	 * @return the member phone number of this u s member
	 */
	@AutoEscape
	public String getMemberPhoneNumber();

	/**
	 * Sets the member phone number of this u s member.
	 *
	 * @param memberPhoneNumber the member phone number of this u s member
	 */
	public void setMemberPhoneNumber(String memberPhoneNumber);

	/**
	 * Gets the member email of this u s member.
	 *
	 * @return the member email of this u s member
	 */
	@AutoEscape
	public String getMemberEmail();

	/**
	 * Sets the member email of this u s member.
	 *
	 * @param memberEmail the member email of this u s member
	 */
	public void setMemberEmail(String memberEmail);

	/**
	 * Gets the member birth date of this u s member.
	 *
	 * @return the member birth date of this u s member
	 */
	public Date getMemberBirthDate();

	/**
	 * Sets the member birth date of this u s member.
	 *
	 * @param memberBirthDate the member birth date of this u s member
	 */
	public void setMemberBirthDate(Date memberBirthDate);

	/**
	 * Gets the company id of this u s member.
	 *
	 * @return the company id of this u s member
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this u s member.
	 *
	 * @param companyId the company id of this u s member
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the group id of this u s member.
	 *
	 * @return the group id of this u s member
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this u s member.
	 *
	 * @param groupId the group id of this u s member
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets a copy of this u s member as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public USMember toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(USMember usMember);

	public int hashCode();

	public String toString();

	public String toXmlString();
}