/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package prueba.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import prueba.model.PhoneNumber;

import prueba.service.MemberLocalService;
import prueba.service.PhoneNumberLocalService;

import prueba.service.persistence.MemberPersistence;
import prueba.service.persistence.PhoneNumberPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the phone number local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link prueba.service.impl.PhoneNumberLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link prueba.service.PhoneNumberLocalServiceUtil} to access the phone number local service.
 * </p>
 *
 * @author Sr. Eladio
 * @see prueba.service.impl.PhoneNumberLocalServiceImpl
 * @see prueba.service.PhoneNumberLocalServiceUtil
 * @generated
 */
public abstract class PhoneNumberLocalServiceBaseImpl
	implements PhoneNumberLocalService {
	/**
	 * Adds the phone number to the database. Also notifies the appropriate model listeners.
	 *
	 * @param phoneNumber the phone number to add
	 * @return the phone number that was added
	 * @throws SystemException if a system exception occurred
	 */
	public PhoneNumber addPhoneNumber(PhoneNumber phoneNumber)
		throws SystemException {
		phoneNumber.setNew(true);

		return phoneNumberPersistence.update(phoneNumber, false);
	}

	/**
	 * Creates a new phone number with the primary key. Does not add the phone number to the database.
	 *
	 * @param numberId the primary key for the new phone number
	 * @return the new phone number
	 */
	public PhoneNumber createPhoneNumber(String numberId) {
		return phoneNumberPersistence.create(numberId);
	}

	/**
	 * Deletes the phone number with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param numberId the primary key of the phone number to delete
	 * @throws PortalException if a phone number with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deletePhoneNumber(String numberId)
		throws PortalException, SystemException {
		phoneNumberPersistence.remove(numberId);
	}

	/**
	 * Deletes the phone number from the database. Also notifies the appropriate model listeners.
	 *
	 * @param phoneNumber the phone number to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deletePhoneNumber(PhoneNumber phoneNumber)
		throws SystemException {
		phoneNumberPersistence.remove(phoneNumber);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return phoneNumberPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return phoneNumberPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return phoneNumberPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return phoneNumberPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the phone number with the primary key.
	 *
	 * @param numberId the primary key of the phone number to get
	 * @return the phone number
	 * @throws PortalException if a phone number with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public PhoneNumber getPhoneNumber(String numberId)
		throws PortalException, SystemException {
		return phoneNumberPersistence.findByPrimaryKey(numberId);
	}

	/**
	 * Gets a range of all the phone numbers.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of phone numbers to return
	 * @param end the upper bound of the range of phone numbers to return (not inclusive)
	 * @return the range of phone numbers
	 * @throws SystemException if a system exception occurred
	 */
	public List<PhoneNumber> getPhoneNumbers(int start, int end)
		throws SystemException {
		return phoneNumberPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of phone numbers.
	 *
	 * @return the number of phone numbers
	 * @throws SystemException if a system exception occurred
	 */
	public int getPhoneNumbersCount() throws SystemException {
		return phoneNumberPersistence.countAll();
	}

	/**
	 * Updates the phone number in the database. Also notifies the appropriate model listeners.
	 *
	 * @param phoneNumber the phone number to update
	 * @return the phone number that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public PhoneNumber updatePhoneNumber(PhoneNumber phoneNumber)
		throws SystemException {
		phoneNumber.setNew(false);

		return phoneNumberPersistence.update(phoneNumber, true);
	}

	/**
	 * Updates the phone number in the database. Also notifies the appropriate model listeners.
	 *
	 * @param phoneNumber the phone number to update
	 * @param merge whether to merge the phone number with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the phone number that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public PhoneNumber updatePhoneNumber(PhoneNumber phoneNumber, boolean merge)
		throws SystemException {
		phoneNumber.setNew(false);

		return phoneNumberPersistence.update(phoneNumber, merge);
	}

	/**
	 * Gets the member local service.
	 *
	 * @return the member local service
	 */
	public MemberLocalService getMemberLocalService() {
		return memberLocalService;
	}

	/**
	 * Sets the member local service.
	 *
	 * @param memberLocalService the member local service
	 */
	public void setMemberLocalService(MemberLocalService memberLocalService) {
		this.memberLocalService = memberLocalService;
	}

	/**
	 * Gets the member persistence.
	 *
	 * @return the member persistence
	 */
	public MemberPersistence getMemberPersistence() {
		return memberPersistence;
	}

	/**
	 * Sets the member persistence.
	 *
	 * @param memberPersistence the member persistence
	 */
	public void setMemberPersistence(MemberPersistence memberPersistence) {
		this.memberPersistence = memberPersistence;
	}

	/**
	 * Gets the phone number local service.
	 *
	 * @return the phone number local service
	 */
	public PhoneNumberLocalService getPhoneNumberLocalService() {
		return phoneNumberLocalService;
	}

	/**
	 * Sets the phone number local service.
	 *
	 * @param phoneNumberLocalService the phone number local service
	 */
	public void setPhoneNumberLocalService(
		PhoneNumberLocalService phoneNumberLocalService) {
		this.phoneNumberLocalService = phoneNumberLocalService;
	}

	/**
	 * Gets the phone number persistence.
	 *
	 * @return the phone number persistence
	 */
	public PhoneNumberPersistence getPhoneNumberPersistence() {
		return phoneNumberPersistence;
	}

	/**
	 * Sets the phone number persistence.
	 *
	 * @param phoneNumberPersistence the phone number persistence
	 */
	public void setPhoneNumberPersistence(
		PhoneNumberPersistence phoneNumberPersistence) {
		this.phoneNumberPersistence = phoneNumberPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = phoneNumberPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = MemberLocalService.class)
	protected MemberLocalService memberLocalService;
	@BeanReference(type = MemberPersistence.class)
	protected MemberPersistence memberPersistence;
	@BeanReference(type = PhoneNumberLocalService.class)
	protected PhoneNumberLocalService phoneNumberLocalService;
	@BeanReference(type = PhoneNumberPersistence.class)
	protected PhoneNumberPersistence phoneNumberPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}