/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.oldschool.user.registration.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.oldschool.user.registration.model.USMember;
import com.oldschool.user.registration.service.USMemberLocalService;
import com.oldschool.user.registration.service.persistence.USMemberPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the u s member local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.oldschool.user.registration.service.impl.USMemberLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.oldschool.user.registration.service.USMemberLocalServiceUtil} to access the u s member local service.
 * </p>
 *
 * @author Sr. Eladio
 * @see com.oldschool.user.registration.service.impl.USMemberLocalServiceImpl
 * @see com.oldschool.user.registration.service.USMemberLocalServiceUtil
 * @generated
 */
public abstract class USMemberLocalServiceBaseImpl
	implements USMemberLocalService {
	/**
	 * Adds the u s member to the database. Also notifies the appropriate model listeners.
	 *
	 * @param usMember the u s member to add
	 * @return the u s member that was added
	 * @throws SystemException if a system exception occurred
	 */
	public USMember addUSMember(USMember usMember) throws SystemException {
		usMember.setNew(true);

		return usMemberPersistence.update(usMember, false);
	}

	/**
	 * Creates a new u s member with the primary key. Does not add the u s member to the database.
	 *
	 * @param memberId the primary key for the new u s member
	 * @return the new u s member
	 */
	public USMember createUSMember(long memberId) {
		return usMemberPersistence.create(memberId);
	}

	/**
	 * Deletes the u s member with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param memberId the primary key of the u s member to delete
	 * @throws PortalException if a u s member with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteUSMember(long memberId)
		throws PortalException, SystemException {
		usMemberPersistence.remove(memberId);
	}

	/**
	 * Deletes the u s member from the database. Also notifies the appropriate model listeners.
	 *
	 * @param usMember the u s member to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteUSMember(USMember usMember) throws SystemException {
		usMemberPersistence.remove(usMember);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return usMemberPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return usMemberPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return usMemberPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return usMemberPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the u s member with the primary key.
	 *
	 * @param memberId the primary key of the u s member to get
	 * @return the u s member
	 * @throws PortalException if a u s member with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public USMember getUSMember(long memberId)
		throws PortalException, SystemException {
		return usMemberPersistence.findByPrimaryKey(memberId);
	}

	/**
	 * Gets a range of all the u s members.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of u s members to return
	 * @param end the upper bound of the range of u s members to return (not inclusive)
	 * @return the range of u s members
	 * @throws SystemException if a system exception occurred
	 */
	public List<USMember> getUSMembers(int start, int end)
		throws SystemException {
		return usMemberPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of u s members.
	 *
	 * @return the number of u s members
	 * @throws SystemException if a system exception occurred
	 */
	public int getUSMembersCount() throws SystemException {
		return usMemberPersistence.countAll();
	}

	/**
	 * Updates the u s member in the database. Also notifies the appropriate model listeners.
	 *
	 * @param usMember the u s member to update
	 * @return the u s member that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public USMember updateUSMember(USMember usMember) throws SystemException {
		usMember.setNew(false);

		return usMemberPersistence.update(usMember, true);
	}

	/**
	 * Updates the u s member in the database. Also notifies the appropriate model listeners.
	 *
	 * @param usMember the u s member to update
	 * @param merge whether to merge the u s member with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the u s member that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public USMember updateUSMember(USMember usMember, boolean merge)
		throws SystemException {
		usMember.setNew(false);

		return usMemberPersistence.update(usMember, merge);
	}

	/**
	 * Gets the u s member local service.
	 *
	 * @return the u s member local service
	 */
	public USMemberLocalService getUSMemberLocalService() {
		return usMemberLocalService;
	}

	/**
	 * Sets the u s member local service.
	 *
	 * @param usMemberLocalService the u s member local service
	 */
	public void setUSMemberLocalService(
		USMemberLocalService usMemberLocalService) {
		this.usMemberLocalService = usMemberLocalService;
	}

	/**
	 * Gets the u s member persistence.
	 *
	 * @return the u s member persistence
	 */
	public USMemberPersistence getUSMemberPersistence() {
		return usMemberPersistence;
	}

	/**
	 * Sets the u s member persistence.
	 *
	 * @param usMemberPersistence the u s member persistence
	 */
	public void setUSMemberPersistence(USMemberPersistence usMemberPersistence) {
		this.usMemberPersistence = usMemberPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = usMemberPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = USMemberLocalService.class)
	protected USMemberLocalService usMemberLocalService;
	@BeanReference(type = USMemberPersistence.class)
	protected USMemberPersistence usMemberPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}